### PR TITLE
Move to the github.com/qpliu/qrencode-go/qrencode package

### LINKED ISSUE #1: Bug: code.google.com/p/rsc/qr no longer valid
As the title suggests, code.google.com/p/rsc/qr is no longer valid. When using this project, one now receives the following error:

`imports code.google.com/p/rsc/qr: unable to detect version control system for code.google.com/ path`

It is due to the fact that code.google.com is officially archived. I am requesting that you export rsc's repo to github and reference that instead.

### PR DESCRIPTION
**Pull request by zaphar**
This package is the most used and starred on gosearch which
is as good a proxy as I could think of for likelihood of support
going forward.

I test generated a png and verified that it was importable into
google authenticator as well as the popular DUO authenticator.

It's a little more work in our code to generate the barcode but not that much really.

Fixes #1

### CODE REVIEW

File: totp.go [hunk 1]
```diff
@@ -38,13 +42,15 @@ func BarcodeImage(label string, secretkey []byte, opt *Options) ([]byte, error)
...
 
-	c, err := qr.Encode(u.String(), qr.M)
+	c, err := qr.Encode(u.String(), qr.ECLevelM)
 
 	if err != nil {
 		return nil, err
 	}
 
-	return c.PNG(), nil
+	buf := bytes.NewBuffer([]byte{})
```
Comment (balasanjay) [inline totp.go]: The zero-value of bytes.Buffer is usable. i.e. this can simply be "var buf bytes.Buffer" (and add an ampersand to the next line).

File: totp.go [hunk 2]
```diff
@@ -38,13 +42,15 @@ func BarcodeImage(label string, secretkey []byte, opt *Options) ([]byte, error)
...
+	err = png.Encode(buf, c.Image(8))
```
Comment (balasanjay) [inline totp.go]: I don't know if this is possible, but if png.Encode writes a partial result to the buffer, then returns an error, then we'll return a non-nil buffer and a non-nil error. To preserve the previous behavior (or atleast to make it obvious that this can't happen), can you add another error check here?

**Comment by balasanjay** [comment]
Thanks! Just a couple of nits, and this looks good to me.

Also, I think if you put "Fixes #1" in the PR description, it'll link and auto-close that issue.

**Comment by zaphar** [comment]
Feedback addressed. Please take another look.

**Comment by balasanjay** [comment]
LGTM. Thanks again!
